override-pv: false
openOnVaultClose: false
disablePurchases: false
gui:
  name: "&f[&4Player Vaults Menu&f]"
  fillitem: "LIGHT_GRAY_STAINED_GLASS_PANE"
unlocked:
  name: "&7[&aUnlocked&7]"
  item: 'GREEN_STAINED_GLASS_PANE'
  lore:
    - "&2&m--------------------"
    - "&f[&4Vault #<VAULTNUM>&f]"
    - "&7[&aLeft-Click&7] To Open"
    - "&2&m--------------------"
locked:
  name: "&7[&cLocked&7]"
  item: 'RED_STAINED_GLASS_PANE'
  lore:
    - "&c&m--------------------"
    - "&f[&4Vault #<VAULTNUM>&f]"
    - "&7[&aLeft-Click&7] To Purchase"
    - "&3Cost&6: &2$&a<COST>"
    - "&c&m--------------------"
key:
  consume: false
  firstJoin: true
  name: "&f[&4Player Vaults Menu&f]"
  item: 'CHEST'
  lore:
    - "&c&m--------------------"
    - "&7Vaults For Players"
    - "&7Hold and Right Click"
    - "&7[&aRight-Click To Open&7]"
    - "&c&m--------------------"
messages:
  buySuccess: "&aYou bought &7Vault #<VAULTNUM>"
  noVaultAccess: "&cPlease buy the previous vault first!"
  vaultLocked: "&cThis vault is locked"
  consumeKey: "&aYou used a menu key"
  insufficientFunds: "&cInsufficient Funds!"
  player404: "&cPlayer not found!"
defaultcost: 10000
defaultMatrix: true
matrix:
  - '         '
  - ' xxxxxxx '
  - 'b       f'
vaults:
  1:
    cost: 250
  2:
    cost: 500
  3:
    cost: 750
  4:
    cost: 1000
  5:
    cost: 1250
  6:
    cost: 1500
  7:
    cost: 1750